[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  GATSBY_TELEMETRY_DISABLED = "1"
  GATSBY_EXPERIMENTAL_LMDB_STORE = "1"
