name: Lighthouse CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Gatsby site
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Run Lighthouse CI - Desktop
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.preset=desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Run Lighthouse CI - Mobile
        run: |
          lhci autorun --collect.preset=mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Archive Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-reports
          path: .lighthouseci/reports/
          retention-days: 30

  lighthouse-netlify-deploy:
    name: Lighthouse CI after Netlify deploy
    runs-on: ubuntu-latest
    needs: lhci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Wait for Netlify deployment
        run: |
          echo "Waiting 60 seconds for Netlify deployment to complete..."
          sleep 60
          
      - name: Run Lighthouse CI against production
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://kowalstwo-karny.pl/
            https://kowalstwo-karny.pl/about
            https://kowalstwo-karny.pl/gallery
            https://kowalstwo-karny.pl/contact
          configPath: '.lighthouseci/lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
